name: pams
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  shared_preferences: ^2.0.5
  another_flushbar: ^1.10.22
  fluttertoast: ^8.0.7
  http:
  connectivity: ^3.0.3
  flutter_riverpod: ^1.0.3
  shimmer: ^2.0.0
  image_picker: ^0.8.3+3
  path_provider: ^2.0.1
  get_storage: ^2.0.3
  dio: ^4.0.0
  flutter_svg: ^0.23.0+1
  sqflite: ^2.0.0+4
  geolocator: ^8.2.0
  permission_handler: ^9.2.0
  intl: ^0.17.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


